server:
  port: 9000

logging:
  level:
    root: info # spring all log
    com.spring.mvcproject: debug # 우리 로그만 deg까지 보겠다

#logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG

spring:
  # file upload setting
  servlet:
    multipart:
      max-file-size: 10MB # 업로드한 하나의 파일의 최대 용량
      max-request-size: 100MB #한 번에 업로드할 수 있는 파일의 총 용량

  #jsp setting
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  # database setting
  datasource:
    url: jdbc:mariadb://localhost:3306/practice
    username: root
    password: mariadb
    driver-class-name: org.mariadb.jdbc.Driver

  # MyBatis 설정
mybatis:
    #sql file location
  mapper-locations: classpath:mapper/**/*.xml
  # /** 이후 경로에 모든 파일/폴더들 /* 파일명이 뭐든지 쓰겠다
  type-aliases-package: com.spring.mvcproject.database.mybatis # 위 패키지 내에 있는 경로에서 찾음
  # 단, 중복 파일 명이 2개일 때 못찾음
  # 보통 설계 시 파일명 유일하게 만듬
  configuration:
   map-underscore-to-camel-case: true

# custom setting - file
# 사용자가 올린 파일들을 어디 저장할거냐?
file:
  upload:
    location: ${user.home}/spring/upload/